version: 2
updates:
  - package-ecosystem: "pnpm"
    directory: "/apps/frontend"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 10
  
  - package-ecosystem: "npm"
    directory: "/apps/backend"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 10
  
  - package-ecosystem: "pnpm"
    directory: "/packages/bridgestars-db-client"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 10
