<script setup>
  const route = useRoute()
  const darkMode = useDarkMode()

  const common = "w-[24px] h-[24px] hover:bg-dash-accent dark:hover:bg-dash-accent hover:animate-shake " //important keep space at the end
  const notificationsOpen = ref(false)

  const isSelected = (item) => route.name == 'dash-'+item;
  const colored = (b) => b ? common + "bg-dash-accent dark:bg-dash-accent" : common + "bg-dark dark:bg-light"
  /*import {Popover} from 'flowbite'*/
  onMounted(()=>{
    /*const popover = new Popover(document.getElementById('popover-target'), {
      placement: 'bottom-end',
      content: document.getElementById('popover-description'),
      trigger: 'click',
      offset: [0, 10],
      interactive: true,
      arrow: true,
      theme: 'light-border',
      appendTo: document.body,
      allowHTML: true,
      zIndex: 1000,
      onShow: () => {
        notificationsOpen.value = true
      },
      onHide: () => {
        notificationsOpen.value = false
      }
    })*/
  })
</script>
<template>
  <div class="bg-dash-light-300 dark:bg-dash-dark flex justify-end flex-grow p-3 space-x-4 h-fit">
    <span 
      :class="`${!darkMode.enabled ? 'i-material-symbols-dark-mode-outline' : 'i-material-symbols-light-mode-outline'}  ${colored(false)}`" 
      @click="darkMode.toggle()"/> 
    <span :class="`i-material-symbols-notifications-outline ${colored(notificationsOpen)}`" id="popover-target"/> 
    <span :class="`i-material-symbols-settings-outline ${colored(isSelected('settings'))}`"/>
    <span :class="`i-ic-baseline-account-circle ${colored(isSelected('profile'))}`"/>
  </div>
  <p class="flex items-center text-sm text-gray-500 dark:text-gray-400">This is just some informational text <button data-popover-target="popover-target" data-popover-placement="bottom-end" type="button"><svg class="w-4 h-4 ml-2 text-gray-400 hover:text-gray-500" aria-hidden="true" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M18 10a8 8 0 11-16 0 8 8 0 0116 0zm-8-3a1 1 0 00-.867.5 1 1 0 11-1.731-1A3 3 0 0113 8a3.001 3.001 0 01-2 2.83V11a1 1 0 11-2 0v-1a1 1 0 011-1 1 1 0 100-2zm0 8a1 1 0 100-2 1 1 0 000 2z" clip-rule="evenodd"></path></svg><span class="sr-only">Show information</span></button></p>
  <div data-popover id="popover-description" role="tooltip" class="absolute z-10 invisible inline-block text-sm text-gray-500 transition-opacity duration-300 bg-white border border-gray-200 rounded-lg shadow-sm opacity-0 w-72 dark:bg-gray-800 dark:border-gray-600 dark:text-gray-400">
      <div class="p-3 space-y-2">
          <h3 class="font-semibold text-gray-900 dark:text-white">Activity growth - Incremental</h3>
          <p>Report helps navigate cumulative growth of community activities. Ideally, the chart should have a growing trend, as stagnating chart signifies a significant decrease of community activity.</p>
          <h3 class="font-semibold text-gray-900 dark:text-white">Calculation</h3>
          <p>For each date bucket, the all-time volume of activities is calculated. This means that activities in period n contain all activities up to period n, plus the activities generated by your community in period.</p>
          <a href="#" class="flex items-center font-medium text-blue-600 dark:text-blue-500 dark:hover:text-blue-600 hover:text-blue-700">Read more <svg class="w-2 h-2 ml-1.5" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 6 10">
      <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m1 9 4-4-4-4"/>
    </svg></a>
      </div>
      <div data-popper-arrow></div>
  </div>
</template>


<style scoped></style>
